name: my_search_app
description: My Search App.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  auto_route: ^5.0.2
  another_flushbar: ^1.10.29 
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1 
  connectivity_plus: ^3.0.2
  catcher: ^0.7.0                   
  dio: ^4.0.6
  equatable: ^2.0.3 
  injectable: ^1.5.3
  intl: ^0.17.0 
  get_it: ^7.2.0 
  flutter_bloc: ^8.1.1
  hydrated_bloc: ^9.0.0
  path_provider: ^2.0.10 
  flutter_screenutil: ^5.6.0
  json_annotation: ^4.7.0
  adaptive_dialog: ^1.6.3
  pull_to_refresh: ^2.0.0 
  flutter_secure_storage: ^6.0.0
  shared_preferences: ^2.0.15
  shimmer: ^2.0.0
  material_design_icons_flutter: ^5.0.5955-rc.1
  sliding_sheet: ^0.5.0
  basic_utils: ^5.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.3.2
  device_preview: ^1.1.0
  auto_route_generator: ^5.0.3
  injectable_generator: ^1.5.3
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.1.0
  flutter_launcher_icons: ^0.11.0
  json_serializable: ^6.5.4
  retrofit_generator: ^4.1.0


flutter:
  uses-material-design: true

  assets:
    - assets/img/background/
    - assets/img/images/
    - assets/img/icon/
    - assets/img/logo/
    - assets/lang/
    - assets/font/

flutter_icons:
  image_path_android: "assets/img/logo/logo_app.png"
  image_path_ios: "assets/img/logo/logo_app.png"
  android: true
  ios: true 
  remove_alpha_ios: true
  adaptive_icon_background: "assets/img/background/icon_bg.png"

flutter_native_splash:
  color: #2283F5"
  image: "assets/img/logo/logo_app.png"
  fullscreen: true
  android12: true